### ISSUE TITLE
Warning when installing .deb package

### ISSUE THREAD

**Issue by fethomm** [omegaui/cliptopia#28]
When trying to install the latest .deb package, postinstall shows a warning: `The creator of a debian package has 100% access to every parts of the system it's installed`

The only things I could find out is that it comes from the app`  flutter_to_debian ` and is invoked if you use `nonInteractive: false`, which seems to be standard. What I could not find out is, what it actually means. Please explain.

**Comment by omegaui** [comment]
Hi! @fethomm,
**.deb** is a system installer package. Every debian package has system wide 100% **read** access, it is because the package needs to be sure whether all required libraries and resources are available.

.deb is standard to install software on debian, ubuntu and their relational distros.

This warning is just a reminder that you should proceed with caution when installing any package.

Cliptopia is **surely safe**, the code is open source for anyone to be sure that it is safe and just designed for clipboard management purpose.

Even after, if you don't want to install cliptopia using *.deb* installer, you can get the **.AppImage** instead from the releases.

**Comment by fethomm** [comment]
Thanks for the explanation. As I am writing an article on Cliptopia, I just wanted to confirm the exact meaning of that message, so I can tell my readers what it means. I have been using Debian Sid for more than 20 years, installing thousands of debs, including 3rd party .debs and have never seen that message before.

**Comment by omegaui** [comment]
Hey Thanks,
Drop me a link when the article is ready.
I would love to read it.

**Comment by fethomm** [comment]
It's an article for the German print magazine LinuxUser. I can send you a PDF once the article is released (~ 6 weeks).
